// USER TYPES
export const FETCH_PLANETS = 'FETCH_PLANETS'
export const FETCH_CHARACTERS = 'FETCH_CHARACTERS'
export const FETCH_STARSHIPS = 'FETCH_STARSHIPS'
export const RECENTLY_VIEWED = 'RECENTLY_VIEWED'
